{application,bencoder,
             [{applications,[kernel,stdlib,elixir]},
              {description,"a library to handle bencode in elixir"},
              {modules,['Elixir.Bencoder','Elixir.Bencoder.Decode',
                        'Elixir.Bencoder.Encode','Elixir.Bencoder.Encoder',
                        'Elixir.Bencoder.Encoder.Atom',
                        'Elixir.Bencoder.Encoder.BitString',
                        'Elixir.Bencoder.Encoder.Integer',
                        'Elixir.Bencoder.Encoder.List',
                        'Elixir.Bencoder.Encoder.Map']},
              {registered,[]},
              {vsn,"0.0.7"}]}.
